Update github-actions to 4.8.1 (#132)
* Always copy php error log into outputs folder to flatten the artifact structure
* Add safe_ref_name handling also for git
* Support checkout for light workflow, too
* Turn off warning in git checkout of the sdk
* Downsize component template
* Add skip_shop_installation option
* Add generic module template
* Fix shop installation check
* Move component settings to install without the shop to the component template
* Only use oe-console from bin or vendor/bin

diff --git a/install_shop/action.yml b/install_shop/action.yml
--- a/install_shop/action.yml
+++ b/install_shop/action.yml
@@ -57,7 +57,16 @@ runs:
       run: |
         # install_shop: Locate Console
         cd source
-        OE_CONSOLE=$(find . -iname "oe-console" -type f|head -1|sed -e "s|^$(pwd)/||")
+        if [ -f 'bin/oe-console' ]; then
+          OE_CONSOLE='bin/bin/oe-console'
+        else
+          if [ -f 'vendor/bin/bin/oe-console' ]; then
+            OE_CONSOLE='vendor/bin/bin/oe-console'
+          else
+            echo -e "\033[0;31mCan't find oe-console in bin or vendor/bin!\033[0m"
+            exit 1
+          fi
+        fi
         echo "OE_CONSOLE=${OE_CONSOLE}"|tee -a "${GITHUB_ENV}"
 
     - name: Run Install Shop
@@ -84,8 +93,12 @@ runs:
       run: |
         # install_shop: Activate iDebug
         ${{ inputs.debug }}
-        perl -pi -e 's#iDebug = 0;#iDebug = -1;#g;' source/source/config.inc.php
-
+        if [ -f source/source/config.inc.php ]; then
+          perl -pi -e 's#iDebug = 0;#iDebug = -1;#g;' source/source/config.inc.php
+        fi
+        if [ -f source/vendor/oxid-esales/oxideshop-ce/source/config.inc.php ]; then
+          perl -pi -e 's#iDebug = 0;#iDebug = -1;#g;' source/vendor/oxid-esales/oxideshop-ce/source/config.inc.php
+        fi
     - name: Activate theme
       if: ${{ inputs.is_enterprise == 'true' }}
       shell: bash
