Only use oe-console from bin or vendor/bin

diff --git a/install_shop/action.yml b/install_shop/action.yml
--- a/install_shop/action.yml
+++ b/install_shop/action.yml
@@ -57,7 +57,16 @@ runs:
       run: |
         # install_shop: Locate Console
         cd source
-        OE_CONSOLE=$(find . -iname "oe-console" -type f|head -1|sed -e "s|^$(pwd)/||")
+        if [ -f 'bin/oe-console' ]; then
+          OE_CONSOLE='bin/bin/oe-console'
+        else
+          if [ -f 'vendor/bin/bin/oe-console' ]; then
+            OE_CONSOLE='vendor/bin/bin/oe-console'
+          else
+            echo -e "\033[0;31mCan't find oe-console in bin or vendor/bin!\033[0m"
+            exit 1
+          fi
+        fi
         echo "OE_CONSOLE=${OE_CONSOLE}"|tee -a "${GITHUB_ENV}"
 
     - name: Run Install Shop
