Add additional_options to phpstan and improve error checking

diff --git a/phpstan/action.yml b/phpstan/action.yml
--- a/phpstan/action.yml
+++ b/phpstan/action.yml
@@ -20,7 +20,12 @@ inputs:
     type: string
     required: false
     default: 'tests/PhpStan/phpstan.neon'
-    description: 'Folder to save the report to'
+    description: 'Configuration file'
+  additional_options:
+    type: string
+    required: false
+    default: '--no-progress'
+    description: 'Additional options to pass to phpstan'
   verbose:
     type: boolean
     required: false
@@ -67,7 +72,8 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Run PHP Mess Detector
+    - name: Run PHPStan
+      id: phpstan
       continue-on-error: true
       shell: bash
       run: |
@@ -75,15 +81,17 @@ runs:
         ${{ inputs.debug }}
         mkdir -p "source/${{inputs.report_path}}"
         echo -e "\033[0;35m###  Generate phpstan-report in ${{ inputs.source_path }} ###\033[0m"
+        set +e
         docker compose ${{ inputs.container_method }} -T \
           ${{ inputs.container_options }} \
           ${{ inputs.container_name }} \
           /var/www/vendor/bin/phpstan \
           -c/var/www/${{inputs.neon_file}} analyse /var/www/${{ inputs.source_path }} \
-          --no-progress \
+          ${{inputs.additional_options}} \
           --error-format=json \
         | cat >source/${{inputs.report_path }}/phpstan-${{ inputs.title }}.json || true
-
+        echo "result=$?" >"${GITHUB_OUTPUT}"
+        set -e
         if [ '${{ inputs.generate_baseline }}' == 'true' ]; then
           echo -e "\033[0;35m###  Generate phpstan baseline for ${{ inputs.source_path }} ###\033[0m"
           docker compose ${{ inputs.container_method }} -T \
@@ -92,19 +100,21 @@ runs:
             /var/www/vendor/bin/phpstan \
             -c/var/www/${{inputs.neon_file}} analyse /var/www/${{ inputs.source_path }} \
             --generate-baseline /var/www/${{inputs.report_path }}/phpstan-${{ inputs.title }}-baseline.neon \
-            --no-progress --quiet \
+            ${{inputs.additional_options}} --quiet \
           || true
         fi
 
         if [ '${{inputs.verbose}}' == 'true' ]; then
           echo -e "\033[0;35m###  Run phpstan in ${{ inputs.source_path }} ###\033[0m"
+          set +e
           docker compose ${{ inputs.container_method }} -T \
             ${{ inputs.container_options }} \
             ${{ inputs.container_name }} \
             /var/www/vendor/bin/phpstan \
             -c/var/www/${{inputs.neon_file}} analyse /var/www/${{ inputs.source_path }} \
-            --no-progress \
+            ${{inputs.additional_options}} \
           | tee -a source/${{inputs.report_path}}/phpstan-${{ inputs.title }}.txt || true
+          set -e
         fi
 
         if [ -s data/php/logs/error_log.txt ]; then
@@ -123,18 +133,28 @@ runs:
     - name: Check results
       shell: bash
       run: |
-        # phpmd: Check results
+        # phpstan: Check results
         ${{ inputs.debug }}
         FILE='source/${{inputs.report_path }}/phpstan-${{ inputs.title }}.json'
-        PURPLE=$(echo -e "\033[0;31m")
-        NOCOLOR=$(echo -e "\033[0m")
-        if [ ! -s "${FILE}" ]; then
-          cat <<EOF
-        ${PURPLE}###############################################################################
-        ### JSON Report is empty! Seems like no tests have been run!
-        ###############################################################################${NOCOLOR}
-        EOF
-          exit 1
+        RESULT=0
+        if [ ${{ steps.phpstan.outputs.result }} -eq 0 ]; then
+          echo -e "\033[0;32m phpstan exited with error code 0"
+          if [ ! -s "${FILE}" ]; then
+            echo -e "\033[0;32m   ${FILE} is empty."
+          else
+            echo -e "\033[0;31m ${FILE} is not empty, please check!"
+            RESULT=1
+          fi
+        else
+          echo -e "\033[0;31m phpstan exited with error code ${{ steps.phpmd.outputs.result }}"
+          RESULT=1
+          if [ ! -s "${FILE}" ]; then
+            echo -e "\033[0;31m ${FILE} is empty!"
+          fi
+        fi
+        if [ -s data/php/logs/error_log.txt ]; then
+          echo -e "\033[0;31m php error log is not empty!"
+          RESULT=1
         fi
         cat >failure_pattern.tmp <<EOF
         ${{ inputs.failure_pattern}}
@@ -144,10 +164,10 @@ runs:
           if [ -n "${LINE}" ]; then
             if grep -q -E "${LINE}" "${FILE}"; then
               echo -e "\033[0;31m phpstan failed matching pattern ${LINE}"
-              grep -E "${LINE}" "${FILE}"
-              exit 1
+              RESULT=1
             else
-                echo -e "\033[0;32m phpstan passed matching pattern ${LINE}"
+              echo -e "\033[0;32m phpstan passed matching pattern ${LINE}"
             fi
           fi
         done <failure_pattern.tmp
+        exit ${RESULT}
