Add phpstan failure pattern handling

diff --git a/phpstan/action.yml b/phpstan/action.yml
--- a/phpstan/action.yml
+++ b/phpstan/action.yml
@@ -51,6 +51,9 @@ inputs:
     required: false
     description: 'Github run artifact for the styles output'
     default: 'phpmd'
+  failure_pattern:
+    "errors":[1-9][0-9]*
+    "file_errors":[1-9][0-9]*
   debug:
     type: string
     description: 'Appended to debugging scripts'
@@ -85,7 +88,7 @@ runs:
             /var/www/vendor/bin/phpstan \
             -c/var/www/${{inputs.neon_file}} analyse /var/www/${{ inputs.source_path }} \
             --generate-baseline /var/www/${{inputs.report_path }}/phpstan-${{ inputs.title }}-baseline.neon \
-            --no-progress --quiet
+            --no-progress --quiet \
           || true
         fi
 
@@ -112,3 +115,35 @@ runs:
         name: ${{ inputs.output_artifact }}
         path: |
           source/${{ inputs.report_path }}*
+
+    - name: Check results
+      shell: bash
+      run: |
+        # phpmd: Check results
+        ${{ inputs.debug }}
+        FILE='source/${{inputs.report_path }}/phpstan-${{ inputs.title }}.json'
+        PURPLE=$(echo -e "\033[0;31m")
+        NOCOLOR=$(echo -e "\033[0m")
+        if [ ! -s "${FILE}" ]; then
+          cat <<EOF
+        ${PURPLE}###############################################################################
+        ### JSON Report is empty! Seems like no tests have been run!
+        ###############################################################################${NOCOLOR}
+        EOF
+          exit 1
+        fi
+        cat >failure_pattern.tmp <<EOF
+        ${{ inputs.failure_pattern}}
+        EOF
+        sed -e 's|(.*)\r|$1|' -i failure_pattern.tmp
+        while read -r LINE ; do
+          if [ -n "${LINE}" ]; then
+            if grep -q -E "${LINE}" "${FILE}"; then
+              echo -e "\033[0;31m phpstan failed matching pattern ${LINE}"
+              grep -E "${LINE}" "${FILE}"
+              exit 1
+            else
+                echo -e "\033[0;32m phpstan passed matching pattern ${LINE}"
+            fi
+          fi
+        done <failure_pattern.tmp
