Handle Tests and tests folders in run_test_script

diff --git a/run_test_script/action.yaml b/run_test_script/action.yaml
--- a/run_test_script/action.yaml
+++ b/run_test_script/action.yaml
@@ -59,7 +59,15 @@ runs:
       run: |
         # run_test_script: Run composer script ${{ inputs.script }}
         ${{ inputs.debug }}
-        mkdir -p source/${{ inputs.path }}/tests/Output source/${{ inputs.path }}/tests/Reports
+        TESTDIR='tests'
+        if [ ! -d "source/${{ inputs.path }}/${TESTDIR}" ]; then
+          TESTDIR='Tests'
+          if [ ! -d "source/${{ inputs.path }}/${TESTDIR}" ]; then
+            echo -e "\033[0;31m###  Could not find folder tests or Tests in ${{ inputs.path }} ###\033[0m"
+            exit 1
+          fi
+        fi
+        mkdir -p source/${{ inputs.path }}/${TESTDIR}/Output source/${{ inputs.path }}/${TESTDIR}/Reports
         echo -e "\033[0;35m###  Run composer ${{ inputs.script }} in ${{ inputs.path }} ###\033[0m"
         docker compose ${{ inputs.container_method }} -T \
           ${{ inputs.container_options }} \
@@ -103,18 +111,26 @@ runs:
       run: |
         # run_test_script: Output php error log
         ${{ inputs.debug }}
+        TESTDIR='tests'
+        if [ ! -d "source/${{ inputs.path }}/${TESTDIR}" ]; then
+          TESTDIR='Tests'
+          if [ ! -d "source/${{ inputs.path }}/${TESTDIR}" ]; then
+            echo -e "\033[0;31m###  Could not find folder tests or Tests in ${{ inputs.path }} ###\033[0m"
+            exit 1
+          fi
+        fi
         if [ -s data/php/logs/error_log.txt ]; then
           echo -e "\033[0;35mPHP error log\033[0m"
           cat data/php/logs/error_log.txt
         fi
         touch data/php/logs/error_log.txt
-        cp data/php/logs/error_log.txt source/${{ inputs.path }}/tests/Output/
-        cp data/mysql/mysql/slow_log* source/${{ inputs.path }}/tests/Output/
-        cp data/mysql/mysql/general_log* source/${{ inputs.path }}/tests/Output/
-        docker compose logs --tail=all >source/${{ inputs.path }}/tests/Output/docker-compose.log
+        cp data/php/logs/error_log.txt source/${{ inputs.path }}/${TESTDIR}/Output/
+        cp data/mysql/mysql/slow_log* source/${{ inputs.path }}/${TESTDIR}/Output/
+        cp data/mysql/mysql/general_log* source/${{ inputs.path }}/${TESTDIR}/Output/
+        docker compose logs --tail=all >source/${{ inputs.path }}/${TESTDIR}/Output/docker-compose.log
         for c in $(docker ps -aq); do
           echo -e "\033[0;35m###  Logs for $c ###\033[0m"
-          docker logs -n 2000 $c >source/${{ inputs.path }}/tests/Output/docker-$c.log
+          docker logs -n 2000 $c >source/${{ inputs.path }}/${TESTDIR}/Output/docker-$c.log
         done
 
     - name: Upload artifact
