Handle Tests and tests folders in run_test_script

diff --git a/run_test_script/action.yaml b/run_test_script/action.yaml
--- a/run_test_script/action.yaml
+++ b/run_test_script/action.yaml
@@ -73,10 +73,18 @@ runs:
       run: |
         # run_test_script: Run shell script ${{ inputs.script }}
         ${{ inputs.debug }}
-        mkdir -p source/${{ inputs.path }}/tests/Output source/${{ inputs.path }}/tests/Reports
-        SCRIPT=$(echo '${{ inputs.script }}'|sed -e "s|^~/|tests/Scripts/|")
+        TESTDIR='tests'
+        if [ ! -d "source/${{ inputs.path }}/${TESTDIR}" ]; then
+          TESTDIR='Tests'
+          if [ ! -d "source/${{ inputs.path }}/${TESTDIR}" ]; then
+            echo -e "\033[0;31m###  Could not find folder tests or Tests in ${{ inputs.path }} ###\033[0m"
+            exit 1
+          fi
+        fi
+        mkdir -p "source/${{ inputs.path }}/${TESTDIR}/Output" "source/${{ inputs.path }}/${TESTDIR}/Reports"
+        SCRIPT=$(echo '${{ inputs.script }}'|sed -e "s|^~/|${TESTDIR}/Scripts/|")
         if [ ! -f "source/${{ inputs.path }}/${SCRIPT}" ]; then
-          SCRIPT=$(echo '${{ inputs.script }}'|sed -e "s|^~/|tests/scripts/|")
+          SCRIPT=$(echo '${{ inputs.script }}'|sed -e "s|^~/|${TESTDIR}/scripts/|")
         fi
         if [ ! -f "source/${{ inputs.path }}/${SCRIPT}" ]; then
           echo -e "\033[0;31m###  Could not find source/${{ inputs.path }}/${SCRIPT} ###\033[0m"
