Add debugging for phpunit, codeception and runtest

diff --git a/codeception/action.yml b/codeception/action.yml
--- a/codeception/action.yml
+++ b/codeception/action.yml
@@ -102,6 +102,16 @@ runs:
           vendor/bin/codecept build \
           -c ${{ inputs.configuration }} \
           ${{ inputs.build_additional_options }}
+        if [ '${{ inputs.debug }}' == 'true' ]; then
+          cat >>debug/debug.sh <<EODS
+            banner "codeception: Build Codeception"
+            docker compose exec -T \\
+              ${{ inputs.container_name}} \\
+              vendor/bin/codecept build \\
+              -c ${{ inputs.configuration }} \\
+              ${{ inputs.build_additional_options }}
+        EODS
+        fi
 
     - name: Run Codeception tests
       shell: bash
@@ -115,6 +125,19 @@ runs:
             --ext DotReporter \
             ${{ inputs.additional_options }} \
             2>&1 | tee ${{ inputs.logfile }} || true
+        if [ '${{ inputs.debug }}' == 'true' ]; then
+          cat >>debug/debug.sh <<EODS
+            banner "codeception: Run Codeception tests"
+            docker compose ${{ inputs.container_method }} -T \\
+              ${{ inputs. container_options }} \\
+              ${{ inputs.container_name}} \\
+              vendor/bin/codecept run ${{ inputs.suite }} ${{ inputs.test }} \\
+                -c ${{ inputs.configuration }} \\
+                --ext DotReporter \\
+                ${{ inputs.additional_options }} \\
+                2>&1 | tee ${{ inputs.logfile }} || true
+        EODS
+        fi
 
     - name: Upload Codeception Artifacts
       if: always()
@@ -145,6 +168,15 @@ runs:
         if [ -s data/php/logs/error_log.txt ]; then
           echo -e "\033[0;35mPHP error log\033[0m"
           cat data/php/logs/error_log.txt
+        fi
+        if [ '${{ inputs.debug }}' == 'true' ]; then
+          cat >>debug/debug.sh <<EODS
+            banner "codeception: Output php error log"
+            if [ -s data/php/logs/error_log.txt ]; then
+              echo -e "\033[0;35mPHP error log\033[0m"
+              cat data/php/logs/error_log.txt
+            fi
+        EODS
         fi
 
     - name: Check results
@@ -183,4 +215,32 @@ runs:
         ###############################################################################
         EOF
           exit 1
+        fi
+        if [ '${{ inputs.debug }}' == 'true' ]; then
+          cat >>debug/debug.sh <<EODS
+            banner "codeception: Check results"
+            if [ ! -s "${{ inputs.logfile }}" ]; then
+              banner "Log file is empty! Seems like no tests have been run!"
+              exit 1
+            fi
+            cat >failure_pattern.tmp <<EOF
+            ${{ inputs.failure_pattern}}
+            EOF
+            sed -e 's|(.*)\\r|\$1|' -i failure_pattern.tmp
+            while read -r LINE ; do
+              if [ -n "\${LINE}" ]; then
+                if grep -q -E "\${LINE}" "${{ inputs.logfile }}"; then
+                  echo -e "\\033[0;31m phpunit test failed matching pattern \${LINE}"
+                  grep -E "\${LINE}" "${{ inputs.logfile }}"
+                  exit 1
+                else
+                    echo -e "\\033[0;32m phpunit test passed matching pattern \${LINE}"
+                fi
+              fi
+            done <failure_pattern.tmp
+            if [[ -n "${{ inputs.coverage_path }}" && ! -s "${{ inputs.coverage_path }}" ]]; then
+              banner "${{ inputs.coverage_path }}" is empty!
+              exit 1
+            fi
+        EODS
         fi
diff --git a/phpunit/action.yml b/phpunit/action.yml
--- a/phpunit/action.yml
+++ b/phpunit/action.yml
@@ -86,6 +86,20 @@ runs:
             "${{ inputs.test }}" \
           | tee "${{ inputs.logfile }}" || true
 
+        if [ '${{ inputs.debug }}' == 'true' ]; then
+          cat >>debug/debug.sh <<EODS
+            banner "phpunit: Run PHPUnit tests"
+            touch "${{ inputs.logfile }}"
+            docker compose ${{ inputs.container_method }} -T ${{ inputs.container_options }} \\
+              ${{ inputs.container_name}} \\
+              php vendor/bin/phpunit \\
+                -c "${{ inputs.configuration }}" \\
+                ${{ inputs.additional_options }} \\
+                "${{ inputs.test }}" \\
+              | tee "${{ inputs.logfile }}" || true
+        EODS
+        fi
+
     - name: Upload Artifacts
       if: always()
       uses: actions/upload-artifact@v4
@@ -116,6 +130,16 @@ runs:
           echo -e "\033[0;35mPHP error log\033[0m"
           cat data/php/logs/error_log.txt
         fi
+        if [ '${{ inputs.debug }}' == 'true' ]; then
+          cat >>debug/debug.sh <<EODS
+            banner "phpunit: Output php error log"
+            if [ -s data/php/logs/error_log.txt ]; then
+              echo -e "\033[0;35mPHP error log\033[0m"
+              cat data/php/logs/error_log.txt
+            fi
+        EODS
+        fi
+
 
     - name: Check results
       shell: bash
@@ -153,4 +177,32 @@ runs:
         ###############################################################################${NOCOLOR}
         EOF
           exit 1
+        fi
+        if [ '${{ inputs.debug }}' == 'true' ]; then
+          cat >>debug/debug.sh <<EODS
+            banner "phpunit: Check results"
+            if [ ! -s "${{ inputs.logfile }}" ]; then
+              banner "Log file is empty! Seems like no tests have been run!"
+              exit 1
+            fi
+            cat >failure_pattern.tmp <<EOF
+            ${{ inputs.failure_pattern}}
+            EOF
+            sed -e 's|(.*)\\r|\$1|' -i failure_pattern.tmp
+            while read -r LINE ; do
+              if [ -n "\${LINE}" ]; then
+                if grep -q -E "\${LINE}" "${{ inputs.logfile }}"; then
+                  echo -e "\\033[0;31m phpunit test failed matching pattern \${LINE}"
+                  grep -E "\${LINE}" "${{ inputs.logfile }}"
+                  exit 1
+                else
+                    echo -e "\\033[0;32m phpunit test passed matching pattern \${LINE}"
+                fi
+              fi
+            done <failure_pattern.tmp
+            if [[ -n "${{ inputs.coverage_path }}" && ! -s "${{ inputs.coverage_path }}" ]]; then
+              banner "${{ inputs.coverage_path }}" is empty!
+              exit 1
+            fi
+        EODS
         fi
diff --git a/runtests/action.yml b/runtests/action.yml
--- a/runtests/action.yml
+++ b/runtests/action.yml
@@ -91,6 +91,14 @@ runs:
         docker compose ${{ inputs.container_method }} -T ${{ inputs.container_options }} \
           ${{ inputs.container_name}} \
           php ${{ inputs.reset_shop_binary }}
+        if [ '${{ inputs.debug }}' == 'true' ]; then
+          cat >>debug/debug.sh <<EODS
+            banner "runtests: Reset shop"
+            docker compose ${{ inputs.container_method }} -T ${{ inputs.container_options }} \\
+              ${{ inputs.container_name}} \\
+              php ${{ inputs.reset_shop_binary }}
+        EODS
+        fi
 
     - name: Run runtest
       shell: bash
@@ -102,6 +110,17 @@ runs:
             ${{ inputs.additional_options }} \
             "${{ inputs.test }}" \
           | tee "${{ inputs.logfile }}" 2>&1 || true
+        if [ '${{ inputs.debug }}' == 'true' ]; then
+          cat >>debug/debug.sh <<EODS
+            banner "runtests: Run runtest"
+            docker compose ${{ inputs.container_method }} -T ${{ inputs.container_options }} \\
+              ${{ inputs.container_name}} \\
+              php ${{ inputs.runtests_binary }} \\
+                ${{ inputs.additional_options }} \\
+                "${{ inputs.test }}" \\
+              | tee "${{ inputs.logfile }}" 2>&1 || true
+        EODS
+        fi
 
     - name: Upload Artifacts
       if: always()
@@ -132,6 +151,15 @@ runs:
         if [ -s data/php/logs/error_log.txt ]; then
           echo -e "\033[0;35mPHP error log\033[0m"
           cat data/php/logs/error_log.txt
+        fi
+        if [ '${{ inputs.debug }}' == 'true' ]; then
+          cat >>debug/debug.sh <<EODS
+            banner "runtests: Output php error log"
+            if [ -s data/php/logs/error_log.txt ]; then
+              echo -e "\033[0;35mPHP error log\033[0m"
+              cat data/php/logs/error_log.txt
+            fi
+        EODS
         fi
 
     - name: Check results
@@ -170,4 +198,32 @@ runs:
         ###############################################################################${NOCOLOR}
         EOF
           exit 1
+        fi
+        if [ '${{ inputs.debug }}' == 'true' ]; then
+          cat >>debug/debug.sh <<EODS
+            banner "runtests: Check results"
+            if [ ! -s "${{ inputs.logfile }}" ]; then
+              banner "Log file is empty! Seems like no tests have been run!"
+              exit 1
+            fi
+            cat >failure_pattern.tmp <<EOF
+            ${{ inputs.failure_pattern}}
+            EOF
+            sed -e 's|(.*)\\r|\$1|' -i failure_pattern.tmp
+            while read -r LINE ; do
+              if [ -n "\${LINE}" ]; then
+                if grep -q -E "\${LINE}" "${{ inputs.logfile }}"; then
+                  echo -e "\\033[0;31m phpunit test failed matching pattern \${LINE}"
+                  grep -E "\${LINE}" "${{ inputs.logfile }}"
+                  exit 1
+                else
+                    echo -e "\\033[0;32m phpunit test passed matching pattern \${LINE}"
+                fi
+              fi
+            done <failure_pattern.tmp
+            if [[ -n "${{ inputs.coverage_path }}" && ! -s "${{ inputs.coverage_path }}" ]]; then
+              banner "${{ inputs.coverage_path }}" is empty!
+              exit 1
+            fi
+        EODS
         fi
