Fix output and env handling and try script capturing

diff --git a/phpunit/action.yml b/phpunit/action.yml
--- a/phpunit/action.yml
+++ b/phpunit/action.yml
@@ -182,8 +182,8 @@ runs:
           cat >>debug/debug.sh <<EODS
             banner "phpunit: Check results"
             if [ ! -s "${{ inputs.logfile }}" ]; then
-              banner "Log file is empty! Seems like no tests have been run!"
-              exit 1
+              banner "Log file is empty! Seems like no tests have been run! Would have exited with an error."
+              # exit 1
             fi
             cat >failure_pattern.tmp <<EOF
             ${{ inputs.failure_pattern}}
@@ -192,17 +192,17 @@ runs:
             while read -r LINE ; do
               if [ -n "\${LINE}" ]; then
                 if grep -q -E "\${LINE}" "${{ inputs.logfile }}"; then
-                  echo -e "\\033[0;31m phpunit test failed matching pattern \${LINE}"
+                  echo -e "\\033[0;31m phpunit test failed matching pattern \${LINE}.  Would have exited with an error."
                   grep -E "\${LINE}" "${{ inputs.logfile }}"
-                  exit 1
+                  # exit 1
                 else
                     echo -e "\\033[0;32m phpunit test passed matching pattern \${LINE}"
                 fi
               fi
             done <failure_pattern.tmp
             if [[ -n "${{ inputs.coverage_path }}" && ! -s "${{ inputs.coverage_path }}" ]]; then
-              banner "${{ inputs.coverage_path }}" is empty!
-              exit 1
+              banner "${{ inputs.coverage_path }} is empty!  Would have exited with an error."
+              # exit 1
             fi
         EODS
         fi
