Move debug generation for install script before script execution

diff --git a/.github/workflows/universal_workflow_light.yaml b/.github/workflows/universal_workflow_light.yaml
--- a/.github/workflows/universal_workflow_light.yaml
+++ b/.github/workflows/universal_workflow_light.yaml
@@ -551,18 +551,6 @@ jobs:
           config_idebug: ${{ steps.iltp.outputs.install_config_idebug }}
           debug: ${{ needs.init.outputs.debug }}
 
-      - name: 'Install shop (script)'
-        if: ${{ steps.iltp.outputs.install_method == 'script' && steps.iltp.outputs.install_skip_shop_installation == 'false' }}
-        run: |
-          SCRIPT="${{ steps.iltp.outputs.install_script }}"
-          if [ -f "${SCRIPT}" ]; then
-            chmod a+x "${SCRIPT}"
-            "${SCRIPT}"
-          else
-            echo -e "\033[0;31mCould not finds ${SCRIPT}\033[0m"
-            exit 1
-          fi
-
       - name: 'Debug Install shop (script)'
         if: ${{ steps.iltp.outputs.install_method == 'script' && steps.iltp.outputs.install_skip_shop_installation == 'false' }}
         run: |
@@ -585,6 +573,18 @@ jobs:
             exit 1
           fi
           EOF
+
+      - name: 'Install shop (script)'
+        if: ${{ steps.iltp.outputs.install_method == 'script' && steps.iltp.outputs.install_skip_shop_installation == 'false' }}
+        run: |
+          SCRIPT="${{ steps.iltp.outputs.install_script }}"
+          if [ -f "${SCRIPT}" ]; then
+            chmod a+x "${SCRIPT}"
+            "${SCRIPT}"
+          else
+            echo -e "\033[0;31mCould not finds ${SCRIPT}\033[0m"
+            exit 1
+          fi
 
       - name: Activate modules
         shell: bash
