Fix install script debugging

diff --git a/.github/workflows/universal_workflow_light.yaml b/.github/workflows/universal_workflow_light.yaml
--- a/.github/workflows/universal_workflow_light.yaml
+++ b/.github/workflows/universal_workflow_light.yaml
@@ -517,7 +517,23 @@ jobs:
       - name: 'Install shop (script)'
         if: ${{ steps.iltp.outputs.install_method == 'script' && steps.iltp.outputs.install_skip_shop_installation == 'false' }}
         run: |
-          ${{ needs.init.outputs.debug }}
+          SCRIPT="source/vendor/oxid-esales/oxideshop-ce/.github/oxid-esales/install.sh"
+          if [ -f "${SCRIPT}" ]; then
+            chmod a+x "${SCRIPT}"
+            "${SCRIPT}"
+          else
+            echo -e "\033[0;31mCould not finds ${SCRIPT}\033[0m"
+            exit 1
+          fi
+
+      - name: 'Debug Install shop (script)'
+        if: ${{ steps.iltp.outputs.install_method == 'script' && steps.iltp.outputs.install_skip_shop_installation == 'false' }}
+        run: |
+          echo "banner 'Install shop (script)'" >>debug/debug.sh
+          for E in $(env|grep -E "^global_|install_|custom_|secrets_"); do
+            echo "export ${E}" >>debug/debug.sh
+          done
+          cat >>debug/debug.sh <<EOF
           SCRIPT="source/vendor/oxid-esales/oxideshop-ce/.github/oxid-esales/install.sh"
           if [ -f "${SCRIPT}" ]; then
             chmod a+x "${SCRIPT}"
@@ -526,7 +542,7 @@ jobs:
           echo -e "\033[0;31mCould not finds ${SCRIPT}\033[0m"
             exit 1
           fi
-
+          EOF
       - name: Activate modules
         shell: bash
         run: |
